/*
 * generated by Xtext
 */
package edu.postech.aadl.xtext.propspec.scoping;

import org.osate.xtext.aadl2.properties.scoping.PropertiesScopeProvider;

/**
 * This class contains custom scoping description.
 *
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 *
 */
public class PropSpecScopeProvider extends PropertiesScopeProvider {

}
