set show timing off .

load ../../interpreter-symbolic2.maude
load module-synchronous-model.maude

mod TEST-MODEL-TRANSITION is
  including TEST-MODEL-TRANSITION-SYSTEM-MOD2 .
  including MODEL-TRANSITION-SYSTEM .

  op initState : -> Object .
  eq initState = initialize(model) .
endm

red initState .

set print attribute on .

search 
	{bool(true) || initState | 0 | 10}  
	=>+ 
	{B:BoolExp || OBJ:Object | T:Time | 10}
	such that 
	check-sat(B:BoolExp and finalConst(OBJ:Object)) . 

