/*
* generated by Xtext
*/
package edu.postech.aadl.xtext.propspec.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PropSpecOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
