load FourDronesSystem_impl_Instance.maude
mod FOURDRONESSYSTEM_IMPL_INSTANCE-MODEL-SYMBOLIC is
	including FOURDRONESSYSTEM_IMPL_INSTANCE-MODEL .
	including BEHAVIOR-SYMBOLIC-LOCATION .
	
	eq output = loc(real(0)) .
	eq init = loc(real(1)) .
	eq exec = loc(real(2)) .
	eq @@default@loc@@ = loc(real(3)) .
	
	eq locName(loc([(0/1).Real])) = 'output .
	eq locName(loc([(1/1).Real])) = 'init .
	eq locName(loc([(2/1).Real])) = 'exec .
	eq locName(loc([(3/1).Real])) = '@@default@loc@@ .
endm
