/*
* generated by Xtext
*/
package edu.postech.aadl.xtext.propspec.ui.contentassist;

import edu.postech.aadl.xtext.propspec.ui.contentassist.AbstractPropSpecProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PropSpecProposalProvider extends AbstractPropSpecProposalProvider {

}
