/*
 * generated by Xtext
 */
package edu.postech.aadl.xtext.propspec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PropSpecRuntimeModule extends edu.postech.aadl.xtext.propspec.AbstractPropSpecRuntimeModule {
	@Override
	public Class<? extends org.eclipse.xtext.linking.ILinkingService> bindILinkingService() {
		return edu.postech.aadl.xtext.propspec.linking.PropSpecLinkingService.class;
	}

	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return org.osate.xtext.aadl2.naming.Aadl2QualifiedNameConverter.class;
	}
}
