
set show timing off .

load ../../interpreter-symbolic2-merge.maude
load module-component-dynamics.maude


mod TEST-ENV-DYNAMICS is
  including TEST-ENV-DYNAMICS-MOD .
  eq @m@ = ['TEST-ENV-DYNAMICS-MOD] .
endm


red finalConst(env1) .

red finalConst(env2) .

--- Test1 : No jump, # controller : 1 
search executeStep(bool(true), env1) =>* C:ConstConfig .

--- Test2 : jump, # controller : 1
search executeStep(bool(true), env2) =>* C:ConstConfig .

--- Test3 : No jump, # controller : 2
search executeStep(bool(true), env3) =>* C:ConstConfig .

--- Test 4 : single jump, controller : 2
search executeStep(bool(true), env4) =>* C:ConstConfig .

--- Test 5 : nondeterministic jump, controller : 2
search executeStep(bool(true), env5) =>* C:ConstConfig .
