
set show timing off .

load ../../interpreter-random.maude
load ../syntax/module-thermostat-hie.maude


---------------------------------------------
mod TEST-THERMOSTAT-SYSTEM-HIE is
  including THERMOSTAT-SYSTEM-SYNTAX .
  including MODEL-TRANSITION-SYSTEM .
  
  op initState : -> Object .
  eq initState = initialize(model) .

  op cinitState : -> Object .
  eq cinitState = initialize(collapse(model)) .
endm


rew {{initState,0} | 0 | 500} .

rew {{initState,400} | 0 | 500} .

rew {{initState,800} | 0 | 500} .

rew {{initState,1200} | 0 | 500} .


rew {{cinitState,0} | 0 | 500} .

rew {{cinitState,400} | 0 | 500} .

rew {{cinitState,800} | 0 | 500} .

rew {{cinitState,1200} | 0 | 500} .
